-- ====================================================================
-- MarketFlow — Consolidated Database Schema & Complete Seed Data
-- Target Database: Supabase PostgreSQL (project: rstjtnrdpfaxlfxqycig)
-- ====================================================================

-- 1. Custom Types & Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DO $$ BEGIN
  CREATE TYPE public.app_role AS ENUM ('global_admin', 'admin', 'stock', 'visitor');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- 2. Profiles (Linked to auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name VARCHAR(150) NOT NULL,
  avatar_url TEXT,
  phone VARCHAR(30),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Trigger: auto-create profile on auth.users sign up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, phone)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    new.raw_user_meta_data->>'avatar_url',
    new.raw_user_meta_data->>'phone'
  )
  ON CONFLICT (id) DO UPDATE
  SET full_name = EXCLUDED.full_name,
      updated_at = now();
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Auto-create profile for any existing auth.users
INSERT INTO public.profiles (id, full_name, created_at, updated_at)
SELECT id, COALESCE(raw_user_meta_data->>'full_name', split_part(email, '@', 1)), now(), now()
FROM auth.users
ON CONFLICT (id) DO NOTHING;

-- 3. Companies (Tenants)
CREATE TABLE IF NOT EXISTS public.companies (
  id TEXT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  legal_name VARCHAR(200),
  cnpj VARCHAR(30),
  slug VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255),
  phone VARCHAR(30),
  whatsapp VARCHAR(30),
  logo_url TEXT,
  description TEXT,
  subtitulo TEXT,
  moeda VARCHAR(10) DEFAULT 'BRL',
  avisoRodape TEXT,
  breakfast_basket_enabled BOOLEAN NOT NULL DEFAULT true,
  active BOOLEAN NOT NULL DEFAULT true,
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

-- 4. Company Users (Tenant Membership & Roles)
CREATE TABLE IF NOT EXISTS public.company_users (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  company_id TEXT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  role public.app_role NOT NULL DEFAULT 'admin',
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT unique_company_user UNIQUE(company_id, user_id)
);

-- 5. Categories
CREATE TABLE IF NOT EXISTS public.categories (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  parent_id TEXT REFERENCES public.categories(id) ON DELETE SET NULL,
  image_url TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

-- 6. Manufacturers (Fabricantes)
CREATE TABLE IF NOT EXISTS public.manufacturers (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name VARCHAR(150) NOT NULL,
  document VARCHAR(30),
  phone VARCHAR(30),
  email VARCHAR(255),
  address TEXT,
  notes TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

-- 7. Brands (Marcas)
CREATE TABLE IF NOT EXISTS public.brands (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  logo_url TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

-- 8. Suppliers (Fornecedores)
CREATE TABLE IF NOT EXISTS public.suppliers (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name VARCHAR(150) NOT NULL,
  legal_name VARCHAR(200),
  cnpj VARCHAR(30),
  email VARCHAR(255),
  phone VARCHAR(30),
  whatsapp VARCHAR(30),
  address TEXT,
  notes TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

-- 9. Products (Produtos com Data de Validade & Vínculos Cesta)
CREATE TABLE IF NOT EXISTS public.products (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  category_id TEXT REFERENCES public.categories(id) ON DELETE SET NULL,
  brand_id TEXT REFERENCES public.brands(id) ON DELETE SET NULL,
  supplier_id TEXT REFERENCES public.suppliers(id) ON DELETE SET NULL,
  manufacturer_id TEXT REFERENCES public.manufacturers(id) ON DELETE SET NULL,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  sku VARCHAR(50),
  barcode VARCHAR(50),
  unit VARCHAR(20) NOT NULL DEFAULT 'UN',
  cost_price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  sale_price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  minimum_stock INTEGER NOT NULL DEFAULT 0,
  maximum_stock INTEGER NOT NULL DEFAULT 0,
  expiration_date DATE,
  active BOOLEAN NOT NULL DEFAULT true,
  catalog_visible BOOLEAN NOT NULL DEFAULT true,
  show_price BOOLEAN NOT NULL DEFAULT true,
  allow_contact BOOLEAN NOT NULL DEFAULT true,
  active_in_basket BOOLEAN NOT NULL DEFAULT true,
  basket_sizes JSONB,
  drink_tier VARCHAR(10),
  image_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

-- 10. Inventory Items (Estoque Consolidado)
CREATE TABLE IF NOT EXISTS public.inventory_items (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 0,
  reserved_quantity INTEGER NOT NULL DEFAULT 0,
  location VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT unique_product_inventory UNIQUE (company_id, product_id)
);

-- 11. Lots (Lotes com Data de Validade)
CREATE TABLE IF NOT EXISTS public.lots (
  id TEXT PRIMARY KEY,
  company_id TEXT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  lot_number VARCHAR(100) NOT NULL,
  initial_quantity INTEGER NOT NULL DEFAULT 0,
  current_quantity INTEGER NOT NULL DEFAULT 0,
  manufacturing_date DATE,
  expiration_date DATE NOT NULL,
  cost_price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 12. Inventory Movements (Kardex / Movimentações de Estoque)
CREATE TABLE IF NOT EXISTS public.inventory_movements (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  company_id TEXT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  product_id TEXT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  lot_id TEXT REFERENCES public.lots(id) ON DELETE SET NULL,
  type VARCHAR(30) NOT NULL, -- 'in', 'out', 'transfer', 'adjustment', 'loss'
  quantity INTEGER NOT NULL,
  previous_quantity INTEGER NOT NULL DEFAULT 0,
  new_quantity INTEGER NOT NULL DEFAULT 0,
  reason TEXT,
  document_reference VARCHAR(100),
  performed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 13. Catalog Requests (Pedidos e Contatos da Loja Pública)
CREATE TABLE IF NOT EXISTS public.catalog_requests (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  company_id TEXT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  customer_name VARCHAR(150) NOT NULL,
  customer_phone VARCHAR(30) NOT NULL,
  customer_email VARCHAR(255),
  total_amount NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  delivery_address TEXT,
  gift_message TEXT,
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  source VARCHAR(50) DEFAULT 'whatsapp_catalog',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ====================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ====================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manufacturers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.catalog_requests ENABLE ROW LEVEL SECURITY;

-- Profiles: Public read, user can update own profile
CREATE POLICY "Profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Companies: Public read for active companies (public store), full access for members
CREATE POLICY "Active companies viewable publicly" ON public.companies FOR SELECT USING (active = true);
CREATE POLICY "Company members full access to company" ON public.companies FOR ALL TO authenticated USING (
  id IN (SELECT company_id FROM public.company_users WHERE user_id = auth.uid()) OR
  created_by = auth.uid()
);

-- Company Users: Authenticated members can view users
CREATE POLICY "Members can view company users" ON public.company_users FOR SELECT TO authenticated USING (true);
CREATE POLICY "Admins can manage company users" ON public.company_users FOR ALL TO authenticated USING (
  company_id IN (
    SELECT company_id FROM public.company_users WHERE user_id = auth.uid() AND role IN ('global_admin', 'admin')
  )
);

-- Generic macro-like policies for tenant tables (public read for store, authenticated edit)
CREATE POLICY "Public read categories" ON public.categories FOR SELECT USING (active = true);
CREATE POLICY "Authenticated manage categories" ON public.categories FOR ALL TO authenticated USING (true);

CREATE POLICY "Public read brands" ON public.brands FOR SELECT USING (active = true);
CREATE POLICY "Authenticated manage brands" ON public.brands FOR ALL TO authenticated USING (true);

CREATE POLICY "Authenticated manage manufacturers" ON public.manufacturers FOR ALL TO authenticated USING (true);
CREATE POLICY "Authenticated manage suppliers" ON public.suppliers FOR ALL TO authenticated USING (true);

CREATE POLICY "Public read products" ON public.products FOR SELECT USING (active = true);
CREATE POLICY "Authenticated manage products" ON public.products FOR ALL TO authenticated USING (true);

CREATE POLICY "Public read inventory" ON public.inventory_items FOR SELECT USING (true);
CREATE POLICY "Authenticated manage inventory" ON public.inventory_items FOR ALL TO authenticated USING (true);

CREATE POLICY "Public read lots" ON public.lots FOR SELECT USING (true);
CREATE POLICY "Authenticated manage lots" ON public.lots FOR ALL TO authenticated USING (true);

CREATE POLICY "Authenticated manage movements" ON public.inventory_movements FOR ALL TO authenticated USING (true);

CREATE POLICY "Public insert catalog requests" ON public.catalog_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Company members view catalog requests" ON public.catalog_requests FOR ALL TO authenticated USING (true);

-- ====================================================================
-- SEED DATA
-- ====================================================================

-- 1. Empresas
INSERT INTO public.companies (
  id, name, legal_name, cnpj, slug, phone, whatsapp, description, subtitulo, moeda, avisoRodape, breakfast_basket_enabled, active
) VALUES
(
  'comp-cesta-1',
  'Cestas de Café da Manhã',
  'Olivelas MarketFlow Comércio Ltda',
  '12.345.678/0001-90',
  'cestas-cafe-da-manha',
  '(11) 96382-0374',
  '5511963820374',
  'Especialista em cestas de café da manhã e presentes para datas especiais.',
  'Monte a sua cesta e envie o pedido pelo WhatsApp',
  'BRL',
  'Cardápio de exemplo — em ajustes.',
  true,
  true
),
(
  'comp-2',
  'Adega & Conveniência Gourmet',
  'Adega Gourmet Eireli',
  '98.765.432/0001-10',
  'adega-gourmet',
  '(11) 91234-5678',
  '5511912345678',
  'Bebidas geladas, aperitivos e conveniência.',
  'Bebidas e produtos selecionados',
  'BRL',
  'Entregas rápidas na região.',
  false,
  true
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  legal_name = EXCLUDED.legal_name,
  cnpj = EXCLUDED.cnpj,
  whatsapp = EXCLUDED.whatsapp,
  breakfast_basket_enabled = EXCLUDED.breakfast_basket_enabled;

-- Vínculo automático de todos os usuários cadastrados como Admin da empresa principal
INSERT INTO public.company_users (company_id, user_id, role, active)
SELECT 'comp-cesta-1', id, 'admin'::public.app_role, true
FROM auth.users
ON CONFLICT (company_id, user_id) DO NOTHING;

-- 2. Categorias
INSERT INTO public.categories (id, company_id, name, description, active) VALUES
('cat-bebidas', 'comp-cesta-1', 'Bebidas', 'Sucos, chás, iogurtes, achocolatados e refrigerantes.', true),
('cat-paes-bolos', 'comp-cesta-1', 'Pães & Bolos', 'Pães artesanais, torradas, croissants e bolos.', true),
('cat-biscoitos', 'comp-cesta-1', 'Biscoitos & Bolachas', 'Wafers, cookies e biscoitos doces e salgados.', true),
('cat-frios-queijos', 'comp-cesta-1', 'Frios & Queijos', 'Queijos selecionados, presunto e requeijão.', true),
('cat-frutas', 'comp-cesta-1', 'Frutas Selecionadas', 'Frutas frescas e higienizadas da estação.', true),
('cat-doces-geleias', 'comp-cesta-1', 'Doces & Geleias', 'Nutella, geleias artesanais e mel.', true),
('cat-chocolates', 'comp-cesta-1', 'Chocolates & Bombons', 'Milka, Ferrero Rocher, Lindt e bombons.', true),
('cat-canecas-brindes', 'comp-cesta-1', 'Canecas & Brindes', 'Itens comemorativos, canecas e cartões de presente.', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- 3. Fornecedores
INSERT INTO public.suppliers (id, company_id, name, legal_name, cnpj, phone, whatsapp, active) VALUES
('sup-1', 'comp-cesta-1', 'Distribuidora Panificação & Doces SP', 'SP Panificação & Alimentos Ltda', '11.222.333/0001-44', '(11) 3333-4444', '5511963820374', true),
('sup-2', 'comp-cesta-1', 'Atacado Hortifruti & Laticínios Central', 'Horti Laticínios Atacadista S.A.', '55.666.777/0001-88', '(11) 2222-1111', '5511963820374', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- 4. Fabricantes
INSERT INTO public.manufacturers (id, company_id, name, document, phone, active) VALUES
('mfg-1', 'comp-cesta-1', 'Ambev S.A.', '07.526.557/0001-00', '(11) 2122-1000', true),
('mfg-2', 'comp-cesta-1', 'Coca-Cola FEMSA Brasil', '45.997.418/0001-53', '0800 021 2121', true),
('mfg-3', 'comp-cesta-1', 'Vinícola Aurora Bento Gonçalves', '87.548.724/0001-30', '(54) 3455-2000', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- 5. Marcas
INSERT INTO public.brands (id, company_id, name, active) VALUES
('brand-1', 'comp-cesta-1', 'Del Valle', true),
('brand-2', 'comp-cesta-1', 'Toddynho', true),
('brand-3', 'comp-cesta-1', 'Kero Coco', true),
('brand-4', 'comp-cesta-1', 'Danone', true),
('brand-5', 'comp-cesta-1', 'Ades', true),
('brand-6', 'comp-cesta-1', 'Natural One', true),
('brand-7', 'comp-cesta-1', 'Antarctica', true),
('brand-8', 'comp-cesta-1', 'Leão', true),
('brand-9', 'comp-cesta-1', 'Aurora', true),
('brand-10', 'comp-cesta-1', 'Maguary', true),
('brand-11', 'comp-cesta-1', 'Pullman', true),
('brand-12', 'comp-cesta-1', 'Wickbold', true),
('brand-13', 'comp-cesta-1', 'Ana Maria', true),
('brand-14', 'comp-cesta-1', 'Forno de Minas', true),
('brand-15', 'comp-cesta-1', 'Padaria', true),
('brand-16', 'comp-cesta-1', 'Trakinas', true),
('brand-17', 'comp-cesta-1', 'Negresco', true),
('brand-18', 'comp-cesta-1', 'Bono', true),
('brand-19', 'comp-cesta-1', 'Passatempo', true),
('brand-20', 'comp-cesta-1', 'Club Social', true),
('brand-21', 'comp-cesta-1', 'Adria', true),
('brand-22', 'comp-cesta-1', 'Bauducco', true),
('brand-23', 'comp-cesta-1', 'Sadia', true),
('brand-24', 'comp-cesta-1', 'Seara', true),
('brand-25', 'comp-cesta-1', 'Tirolez', true),
('brand-26', 'comp-cesta-1', 'Catupiry', true),
('brand-27', 'comp-cesta-1', 'Queensberry', true),
('brand-28', 'comp-cesta-1', 'Nutella', true),
('brand-29', 'comp-cesta-1', 'Aviação', true),
('brand-30', 'comp-cesta-1', 'Karo', true),
('brand-31', 'comp-cesta-1', 'Yoki', true),
('brand-32', 'comp-cesta-1', 'Hortifruti', true),
('brand-33', 'comp-cesta-1', 'Pilão', true),
('brand-34', 'comp-cesta-1', '3 Corações', true),
('brand-35', 'comp-cesta-1', 'Twinings', true),
('brand-36', 'comp-cesta-1', 'União', true),
('brand-37', 'comp-cesta-1', 'Salton', true),
('brand-38', 'comp-cesta-1', 'Pérgola', true),
('brand-39', 'comp-cesta-1', 'Lindt', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- 6. Produtos (Todos os 51 Itens Oficiais com Validade Real)
INSERT INTO public.products (
  id, company_id, category_id, brand_id, name, description, sku, barcode, unit,
  cost_price, sale_price, minimum_stock, maximum_stock, expiration_date,
  active, catalog_visible, show_price, allow_contact, active_in_basket, basket_sizes, drink_tier
) VALUES
(
  'beb-suco-delvalle-200',
  'comp-cesta-1',
  'cat-bebidas',
  'brand-1',
  'Suco Del Valle Uva 200 ml',
  'Suco Del Valle Uva 200 ml (Del Valle). Ideal para montagem de cestas matinais personalizadas.',
  'BEB-SUCO-DELVALLE-200',
  '7897957234103',
  'UN',
  2.69,
  4.49,
  5,
  50,
  '2026-11-05',
  true,
  true,
  true,
  true,
  true,
  '["pequena"]'::jsonb,
  'P'
),
(
  'beb-toddynho-200',
  'comp-cesta-1',
  'cat-bebidas',
  'brand-2',
  'Achocolatado Toddynho 200 ml',
  'Achocolatado Toddynho 200 ml (Toddynho). Ideal para montagem de cestas matinais personalizadas.',
  'BEB-TODDYNHO-200',
  '7893231774002',
  'UN',
  1.97,
  3.29,
  5,
  50,
  '2026-11-20',
  true,
  true,
  true,
  true,
  true,
  '["pequena"]'::jsonb,
  'P'
),
(
  'beb-agua-coco-200',
  'comp-cesta-1',
  'cat-bebidas',
  'brand-3',
  'Água de Coco Kero Coco 200 ml',
  'Água de Coco Kero Coco 200 ml (Kero Coco). Ideal para montagem de cestas matinais personalizadas.',
  'BEB-AGUA-COCO-200',
  '7892908327126',
  'UN',
  2.99,
  4.99,
  5,
  50,
  '2026-12-05',
  true,
  true,
  true,
  true,
  true,
  '["pequena"]'::jsonb,
  'P'
),
(
  'beb-iog-danone-170',
  'comp-cesta-1',
  'cat-bebidas',
  'brand-4',
  'Iogurte Líquido Danone 170 g',
  'Iogurte Líquido Danone 170 g (Danone). Ideal para montagem de cestas matinais personalizadas.',
  'BEB-IOG-DANONE-170',
  '7893753568948',
  'UN',
  2.27,
  3.79,
  5,
  50,
  '2026-09-13',
  true,
  true,
  true,
  true,
  true,
  '["pequena"]'::jsonb,
  'P'
),
(
  'beb-ades-500',
  'comp-cesta-1',
  'cat-bebidas',
  'brand-5',
  'Bebida de Soja Ades Maçã 500 ml',
  'Bebida de Soja Ades Maçã 500 ml (Ades). Ideal para montagem de cestas matinais personalizadas.',
  'BEB-ADES-500',
  '7893409928575',
  'UN',
  3.89,
  6.49,
  5,
  50,
  '2026-10-21',
  true,
  true,
  true,
  true,
  true,
  '["media"]'::jsonb,
  'M'
),
(
  'beb-suco-natone-500',
  'comp-cesta-1',
  'cat-bebidas',
  'brand-6',
  'Suco Natural One Laranja 500 ml',
  'Suco Natural One Laranja 500 ml (Natural One). Ideal para montagem de cestas matinais personalizadas.',
  'BEB-SUCO-NATONE-500',
  '7897086926449',
  'UN',
  6.54,
  10.90,
  5,
  50,
  '2026-09-20',
  true,
  true,
  true,
  true,
  true,
  '["media"]'::jsonb,
  'M'
),
(
  'beb-guarana-350',
  'comp-cesta-1',
  'cat-bebidas',
  'brand-7',
  'Guaraná Antarctica 350 ml (lata)',
  'Guaraná Antarctica 350 ml (lata) (Antarctica). Ideal para montagem de cestas matinais personalizadas.',
  'BEB-GUARANA-350',
  '7897924077700',
  'UN',
  2.99,
  4.99,
  5,
  50,
  '2027-03-05',
  true,
  true,
  true,
  true,
  true,
  '["media"]'::jsonb,
  'M'
),
(
  'beb-cha-leao-450',
  'comp-cesta-1',
  'cat-bebidas',
  'brand-8',
  'Chá Leão Pêssego 450 ml',
  'Chá Leão Pêssego 450 ml (Leão). Ideal para montagem de cestas matinais personalizadas.',
  'BEB-CHA-LEAO-450',
  '7892626148523',
  'UN',
  4.14,
  6.90,
  5,
  50,
  '2026-12-05',
  true,
  true,
  true,
  true,
  true,
  '["media"]'::jsonb,
  'M'
),
(
  'beb-suco-aurora-1l',
  'comp-cesta-1',
  'cat-bebidas',
  'brand-9',
  'Suco de Uva Integral Aurora 1 L',
  'Suco de Uva Integral Aurora 1 L (Aurora). Ideal para montagem de cestas matinais personalizadas.',
  'BEB-SUCO-AURORA-1L',
  '7896755628176',
  'UN',
  11.34,
  18.90,
  5,
  50,
  '2027-01-04',
  true,
  true,
  true,
  true,
  true,
  '["grande"]'::jsonb,
  'G'
),
(
  'beb-maguary-1l',
  'comp-cesta-1',
  'cat-bebidas',
  'brand-10',
  'Néctar Maguary Manga 1 L',
  'Néctar Maguary Manga 1 L (Maguary). Ideal para montagem de cestas matinais personalizadas.',
  'BEB-MAGUARY-1L',
  '7893922152857',
  'UN',
  5.94,
  9.90,
  5,
  50,
  '2026-12-15',
  true,
  true,
  true,
  true,
  true,
  '["grande"]'::jsonb,
  'G'
),
(
  'beb-guarana-1l',
  'comp-cesta-1',
  'cat-bebidas',
  'brand-7',
  'Guaraná Antarctica 1 L',
  'Guaraná Antarctica 1 L (Antarctica). Ideal para montagem de cestas matinais personalizadas.',
  'BEB-GUARANA-1L',
  '7899988353911',
  'UN',
  5.09,
  8.49,
  5,
  50,
  '2027-03-05',
  true,
  true,
  true,
  true,
  true,
  '["grande"]'::jsonb,
  'G'
),
(
  'pb-pao-forma-pullman',
  'comp-cesta-1',
  'cat-paes-bolos',
  'brand-11',
  'Pão de Forma Pullman 100% Integral',
  'Pão de Forma Pullman 100% Integral (Pullman). Ideal para montagem de cestas matinais personalizadas.',
  'PB-PAO-FORMA-PULLMAN',
  '7897529762833',
  'UN',
  5.94,
  9.90,
  5,
  50,
  '2026-09-20',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'pb-bisnaguinha-wickbold',
  'comp-cesta-1',
  'cat-paes-bolos',
  'brand-12',
  'Bisnaguinha Wickbold',
  'Bisnaguinha Wickbold (Wickbold). Ideal para montagem de cestas matinais personalizadas.',
  'PB-BISNAGUINHA-WICKBOLD',
  '7892983482294',
  'UN',
  4.49,
  7.49,
  5,
  50,
  '2026-09-24',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'pb-bolo-anamaria',
  'comp-cesta-1',
  'cat-paes-bolos',
  'brand-13',
  'Bolinho Ana Maria (unid.)',
  'Bolinho Ana Maria (unid.) (Ana Maria). Ideal para montagem de cestas matinais personalizadas.',
  'PB-BOLO-ANAMARIA',
  '7896541425704',
  'UN',
  2.09,
  3.49,
  5,
  50,
  '2026-10-06',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'pb-pao-queijo-fdm',
  'comp-cesta-1',
  'cat-paes-bolos',
  'brand-14',
  'Pão de Queijo Forno de Minas 400 g',
  'Pão de Queijo Forno de Minas 400 g (Forno de Minas). Ideal para montagem de cestas matinais personalizadas.',
  'PB-PAO-QUEIJO-FDM',
  '7896616785174',
  'UN',
  10.14,
  16.90,
  5,
  50,
  '2026-12-05',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
),
(
  'pb-croissant',
  'comp-cesta-1',
  'cat-paes-bolos',
  NULL,
  'Croissant Folhado (unid.)',
  'Croissant Folhado (unid.) (Padaria). Ideal para montagem de cestas matinais personalizadas.',
  'PB-CROISSANT',
  '7896666662901',
  'UN',
  3.30,
  5.50,
  5,
  50,
  '2026-09-09',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
),
(
  'pb-rosca-coco',
  'comp-cesta-1',
  'cat-paes-bolos',
  NULL,
  'Rosca de Coco (unid.)',
  'Rosca de Coco (unid.) (Padaria). Ideal para montagem de cestas matinais personalizadas.',
  'PB-ROSCA-COCO',
  '7897991297927',
  'UN',
  7.74,
  12.90,
  5,
  50,
  '2026-09-11',
  true,
  true,
  true,
  true,
  true,
  '["grande"]'::jsonb,
  NULL
),
(
  'bis-trakinas-morango',
  'comp-cesta-1',
  'cat-biscoitos',
  'brand-16',
  'Biscoito Recheado Trakinas Morango',
  'Biscoito Recheado Trakinas Morango (Trakinas). Ideal para montagem de cestas matinais personalizadas.',
  'BIS-TRAKINAS-MORANGO',
  '7899235059259',
  'UN',
  1.91,
  3.19,
  5,
  50,
  '2027-02-03',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'bis-negresco',
  'comp-cesta-1',
  'cat-biscoitos',
  'brand-17',
  'Biscoito Recheado Negresco',
  'Biscoito Recheado Negresco (Negresco). Ideal para montagem de cestas matinais personalizadas.',
  'BIS-NEGRESCO',
  '7893905826382',
  'UN',
  2.09,
  3.49,
  5,
  50,
  '2027-02-03',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'bis-bono-choc',
  'comp-cesta-1',
  'cat-biscoitos',
  'brand-18',
  'Biscoito Bono Chocolate',
  'Biscoito Bono Chocolate (Bono). Ideal para montagem de cestas matinais personalizadas.',
  'BIS-BONO-CHOC',
  '7898960948013',
  'UN',
  1.97,
  3.29,
  5,
  50,
  '2027-02-03',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'bis-passatempo',
  'comp-cesta-1',
  'cat-biscoitos',
  'brand-19',
  'Biscoito Recheado Passatempo',
  'Biscoito Recheado Passatempo (Passatempo). Ideal para montagem de cestas matinais personalizadas.',
  'BIS-PASSATEMPO',
  '7899028590079',
  'UN',
  2.03,
  3.39,
  5,
  50,
  '2027-02-03',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'bis-club-social',
  'comp-cesta-1',
  'cat-biscoitos',
  'brand-20',
  'Biscoito Club Social Original (6x)',
  'Biscoito Club Social Original (6x) (Club Social). Ideal para montagem de cestas matinais personalizadas.',
  'BIS-CLUB-SOCIAL',
  '7895813558342',
  'UN',
  3.29,
  5.49,
  5,
  50,
  '2026-12-05',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'bis-cream-cracker-adria',
  'comp-cesta-1',
  'cat-biscoitos',
  'brand-21',
  'Cream Cracker Adria',
  'Cream Cracker Adria (Adria). Ideal para montagem de cestas matinais personalizadas.',
  'BIS-CREAM-CRACKER-ADRIA',
  '7894970636128',
  'UN',
  2.57,
  4.29,
  5,
  50,
  '2027-01-04',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'bis-waffer-bauducco',
  'comp-cesta-1',
  'cat-biscoitos',
  'brand-22',
  'Wafer Bauducco Chocolate',
  'Wafer Bauducco Chocolate (Bauducco). Ideal para montagem de cestas matinais personalizadas.',
  'BIS-WAFFER-BAUDUCCO',
  '7897080308554',
  'UN',
  2.27,
  3.79,
  5,
  50,
  '2027-02-03',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
),
(
  'fq-queijo-prato-sadia',
  'comp-cesta-1',
  'cat-frios-queijos',
  'brand-23',
  'Queijo Prato Fatiado Sadia 150 g',
  'Queijo Prato Fatiado Sadia 150 g (Sadia). Ideal para montagem de cestas matinais personalizadas.',
  'FQ-QUEIJO-PRATO-SADIA',
  '7896283019734',
  'UN',
  7.74,
  12.90,
  5,
  50,
  '2026-09-18',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
),
(
  'fq-presunto-seara',
  'comp-cesta-1',
  'cat-frios-queijos',
  'brand-24',
  'Presunto Cozido Fatiado Seara 150 g',
  'Presunto Cozido Fatiado Seara 150 g (Seara). Ideal para montagem de cestas matinais personalizadas.',
  'FQ-PRESUNTO-SEARA',
  '7894103372034',
  'UN',
  5.94,
  9.90,
  5,
  50,
  '2026-09-11',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
),
(
  'fq-mussarela-tirolez',
  'comp-cesta-1',
  'cat-frios-queijos',
  'brand-25',
  'Mussarela Fatiada Tirolez 150 g',
  'Mussarela Fatiada Tirolez 150 g (Tirolez). Ideal para montagem de cestas matinais personalizadas.',
  'FQ-MUSSARELA-TIROLEZ',
  '7894418573756',
  'UN',
  8.10,
  13.50,
  5,
  50,
  '2026-09-21',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
),
(
  'fq-requeijao-catupiry',
  'comp-cesta-1',
  'cat-frios-queijos',
  'brand-26',
  'Requeijão Catupiry 200 g',
  'Requeijão Catupiry 200 g (Catupiry). Ideal para montagem de cestas matinais personalizadas.',
  'FQ-REQUEIJAO-CATUPIRY',
  '7891667473260',
  'UN',
  7.14,
  11.90,
  5,
  50,
  '2026-10-16',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'dg-geleia-queensberry',
  'comp-cesta-1',
  'cat-doces-geleias',
  'brand-27',
  'Geleia Queensberry Morango 320 g',
  'Geleia Queensberry Morango 320 g (Queensberry). Ideal para montagem de cestas matinais personalizadas.',
  'DG-GELEIA-QUEENSBERRY',
  '7893820735605',
  'UN',
  9.54,
  15.90,
  5,
  50,
  '2027-07-03',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'dg-nutella-140',
  'comp-cesta-1',
  'cat-doces-geleias',
  'brand-28',
  'Creme de Avelã Nutella 140 g',
  'Creme de Avelã Nutella 140 g (Nutella). Ideal para montagem de cestas matinais personalizadas.',
  'DG-NUTELLA-140',
  '7894997078515',
  'UN',
  8.34,
  13.90,
  5,
  50,
  '2027-07-03',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'dg-doce-leite-aviacao',
  'comp-cesta-1',
  'cat-doces-geleias',
  'brand-29',
  'Doce de Leite Aviação 400 g',
  'Doce de Leite Aviação 400 g (Aviação). Ideal para montagem de cestas matinais personalizadas.',
  'DG-DOCE-LEITE-AVIACAO',
  '7898986407976',
  'UN',
  7.50,
  12.50,
  5,
  50,
  '2027-07-03',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
),
(
  'dg-mel-karo',
  'comp-cesta-1',
  'cat-doces-geleias',
  'brand-30',
  'Mel Karo Squeeze 200 g',
  'Mel Karo Squeeze 200 g (Karo). Ideal para montagem de cestas matinais personalizadas.',
  'DG-MEL-KARO',
  '7898634541351',
  'UN',
  8.94,
  14.90,
  5,
  50,
  '2027-07-03',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
),
(
  'dg-pacoca-yoki',
  'comp-cesta-1',
  'cat-doces-geleias',
  'brand-31',
  'Paçoca Rolha Yoki (unid.)',
  'Paçoca Rolha Yoki (unid.) (Yoki). Ideal para montagem de cestas matinais personalizadas.',
  'DG-PACOCA-YOKI',
  '7897212311014',
  'UN',
  0.77,
  1.29,
  5,
  50,
  '2027-07-03',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'fr-maca',
  'comp-cesta-1',
  'cat-frutas',
  NULL,
  'Maçã Gala (unid.)',
  'Maçã Gala (unid.) (Hortifruti). Ideal para montagem de cestas matinais personalizadas.',
  'FR-MACA',
  '7899350460725',
  'UN',
  1.19,
  1.99,
  5,
  50,
  '2026-09-18',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'fr-banana',
  'comp-cesta-1',
  'cat-frutas',
  NULL,
  'Banana Prata (unid.)',
  'Banana Prata (unid.) (Hortifruti). Ideal para montagem de cestas matinais personalizadas.',
  'FR-BANANA',
  '7895023876984',
  'UN',
  0.77,
  1.29,
  5,
  50,
  '2026-09-18',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'fr-uva-verde',
  'comp-cesta-1',
  'cat-frutas',
  NULL,
  'Uva Verde sem Semente (150 g)',
  'Uva Verde sem Semente (150 g) (Hortifruti). Ideal para montagem de cestas matinais personalizadas.',
  'FR-UVA-VERDE',
  '7893655068095',
  'UN',
  4.14,
  6.90,
  5,
  50,
  '2026-09-18',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
),
(
  'fr-morango-bandeja',
  'comp-cesta-1',
  'cat-frutas',
  NULL,
  'Morango Bandeja 250 g',
  'Morango Bandeja 250 g (Hortifruti). Ideal para montagem de cestas matinais personalizadas.',
  'FR-MORANGO-BANDEJA',
  '7891829961494',
  'UN',
  5.94,
  9.90,
  5,
  50,
  '2026-09-18',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
),
(
  'fr-kiwi',
  'comp-cesta-1',
  'cat-frutas',
  NULL,
  'Kiwi (unid.)',
  'Kiwi (unid.) (Hortifruti). Ideal para montagem de cestas matinais personalizadas.',
  'FR-KIWI',
  '7898386399745',
  'UN',
  1.49,
  2.49,
  5,
  50,
  '2026-09-18',
  true,
  true,
  true,
  true,
  true,
  '["grande"]'::jsonb,
  NULL
),
(
  'mc-cafe-pilao-sache',
  'comp-cesta-1',
  'cat-mercearia-cafe',
  'brand-33',
  'Café Pilão em sachê (10 g)',
  'Café Pilão em sachê (10 g) (Pilão). Ideal para montagem de cestas matinais personalizadas.',
  'MC-CAFE-PILAO-SACHE',
  '7896985126725',
  'UN',
  0.89,
  1.49,
  5,
  50,
  '2026-11-05',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'mc-capuccino-3coracoes',
  'comp-cesta-1',
  'cat-mercearia-cafe',
  'brand-34',
  'Cappuccino 3 Corações Sachê',
  'Cappuccino 3 Corações Sachê (3 Corações). Ideal para montagem de cestas matinais personalizadas.',
  'MC-CAPUCCINO-3CORACOES',
  '7899589801780',
  'UN',
  1.49,
  2.49,
  5,
  50,
  '2026-11-05',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'mc-cha-twinings',
  'comp-cesta-1',
  'cat-mercearia-cafe',
  'brand-35',
  'Chá Twinings (cx. 10 saquinhos)',
  'Chá Twinings (cx. 10 saquinhos) (Twinings). Ideal para montagem de cestas matinais personalizadas.',
  'MC-CHA-TWININGS',
  '7894737706760',
  'UN',
  7.14,
  11.90,
  5,
  50,
  '2026-11-05',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
),
(
  'mc-manteiga-aviacao',
  'comp-cesta-1',
  'cat-mercearia-cafe',
  'brand-29',
  'Manteiga Aviação 200 g',
  'Manteiga Aviação 200 g (Aviação). Ideal para montagem de cestas matinais personalizadas.',
  'MC-MANTEIGA-AVIACAO',
  '7899158101218',
  'UN',
  8.34,
  13.90,
  5,
  50,
  '2026-11-05',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
),
(
  'mc-acucar-sache',
  'comp-cesta-1',
  'cat-mercearia-cafe',
  NULL,
  'Açúcar refinado em sachês (10x)',
  'Açúcar refinado em sachês (10x) (União). Ideal para montagem de cestas matinais personalizadas.',
  'MC-ACUCAR-SACHE',
  '7899735684906',
  'UN',
  2.34,
  3.90,
  5,
  50,
  '2026-11-05',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'ad-caneca',
  'comp-cesta-1',
  'cat-adicionais',
  NULL,
  'Caneca personalizada',
  'Caneca personalizada (Sem marca). Ideal para montagem de cestas matinais personalizadas.',
  'AD-CANECA',
  '7893670651223',
  'UN',
  14.94,
  24.90,
  5,
  50,
  '2026-11-05',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'ad-cartao',
  'comp-cesta-1',
  'cat-adicionais',
  NULL,
  'Cartão com mensagem',
  'Cartão com mensagem (Sem marca). Ideal para montagem de cestas matinais personalizadas.',
  'AD-CARTAO',
  '7891132746481',
  'UN',
  3.00,
  5.00,
  5,
  50,
  '2026-11-05',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'ad-balao',
  'comp-cesta-1',
  'cat-adicionais',
  NULL,
  'Balão metalizado',
  'Balão metalizado (Sem marca). Ideal para montagem de cestas matinais personalizadas.',
  'AD-BALAO',
  '7894470786153',
  'UN',
  8.94,
  14.90,
  5,
  50,
  '2026-11-05',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'ad-mini-buque',
  'comp-cesta-1',
  'cat-adicionais',
  NULL,
  'Mini buquê de flores',
  'Mini buquê de flores (Sem marca). Ideal para montagem de cestas matinais personalizadas.',
  'AD-MINI-BUQUE',
  '7896631175255',
  'UN',
  17.94,
  29.90,
  5,
  50,
  '2026-11-05',
  true,
  true,
  true,
  true,
  true,
  '["pequena","media","grande"]'::jsonb,
  NULL
),
(
  'ad-espumante',
  'comp-cesta-1',
  'cat-adicionais',
  'brand-37',
  'Mini Espumante Salton 187 ml',
  'Mini Espumante Salton 187 ml (Salton). Ideal para montagem de cestas matinais personalizadas.',
  'AD-ESPUMANTE',
  '7895936250898',
  'UN',
  13.74,
  22.90,
  5,
  50,
  '2026-11-05',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
),
(
  'ad-vinho-pergola',
  'comp-cesta-1',
  'cat-adicionais',
  'brand-38',
  'Vinho Pérgola Tinto Suave 750 ml',
  'Vinho Pérgola Tinto Suave 750 ml (Pérgola). Ideal para montagem de cestas matinais personalizadas.',
  'AD-VINHO-PERGOLA',
  '7896446577003',
  'UN',
  17.94,
  29.90,
  5,
  50,
  '2026-11-05',
  true,
  true,
  true,
  true,
  true,
  '["grande"]'::jsonb,
  NULL
),
(
  'ad-chocolate-lindt',
  'comp-cesta-1',
  'cat-adicionais',
  'brand-39',
  'Chocolate Lindt Lindor 100 g',
  'Chocolate Lindt Lindor 100 g (Lindt). Ideal para montagem de cestas matinais personalizadas.',
  'AD-CHOCOLATE-LINDT',
  '7897890119493',
  'UN',
  20.94,
  34.90,
  5,
  50,
  '2026-11-05',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
),
(
  'ad-taca',
  'comp-cesta-1',
  'cat-adicionais',
  NULL,
  'Par de taças de vidro',
  'Par de taças de vidro (Sem marca). Ideal para montagem de cestas matinais personalizadas.',
  'AD-TACA',
  '7893070554198',
  'UN',
  11.94,
  19.90,
  5,
  50,
  '2026-11-05',
  true,
  true,
  true,
  true,
  true,
  '["media","grande"]'::jsonb,
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  sale_price = EXCLUDED.sale_price,
  cost_price = EXCLUDED.cost_price,
  expiration_date = EXCLUDED.expiration_date,
  active_in_basket = EXCLUDED.active_in_basket,
  basket_sizes = EXCLUDED.basket_sizes,
  drink_tier = EXCLUDED.drink_tier;

-- 7. Estoque Inicial (25 unidades de cada produto)
INSERT INTO public.inventory_items (id, company_id, product_id, quantity, reserved_quantity, location) VALUES
('inv-beb-suco-delvalle-200', 'comp-cesta-1', 'beb-suco-delvalle-200', 25, 0, 'Prateleira A'),
('inv-beb-toddynho-200', 'comp-cesta-1', 'beb-toddynho-200', 25, 0, 'Prateleira A'),
('inv-beb-agua-coco-200', 'comp-cesta-1', 'beb-agua-coco-200', 25, 0, 'Prateleira A'),
('inv-beb-iog-danone-170', 'comp-cesta-1', 'beb-iog-danone-170', 25, 0, 'Prateleira A'),
('inv-beb-ades-500', 'comp-cesta-1', 'beb-ades-500', 25, 0, 'Prateleira A'),
('inv-beb-suco-natone-500', 'comp-cesta-1', 'beb-suco-natone-500', 25, 0, 'Prateleira A'),
('inv-beb-guarana-350', 'comp-cesta-1', 'beb-guarana-350', 25, 0, 'Prateleira A'),
('inv-beb-cha-leao-450', 'comp-cesta-1', 'beb-cha-leao-450', 25, 0, 'Prateleira A'),
('inv-beb-suco-aurora-1l', 'comp-cesta-1', 'beb-suco-aurora-1l', 25, 0, 'Prateleira A'),
('inv-beb-maguary-1l', 'comp-cesta-1', 'beb-maguary-1l', 25, 0, 'Prateleira A'),
('inv-beb-guarana-1l', 'comp-cesta-1', 'beb-guarana-1l', 25, 0, 'Prateleira A'),
('inv-pb-pao-forma-pullman', 'comp-cesta-1', 'pb-pao-forma-pullman', 25, 0, 'Prateleira A'),
('inv-pb-bisnaguinha-wickbold', 'comp-cesta-1', 'pb-bisnaguinha-wickbold', 25, 0, 'Prateleira A'),
('inv-pb-bolo-anamaria', 'comp-cesta-1', 'pb-bolo-anamaria', 25, 0, 'Prateleira A'),
('inv-pb-pao-queijo-fdm', 'comp-cesta-1', 'pb-pao-queijo-fdm', 25, 0, 'Prateleira A'),
('inv-pb-croissant', 'comp-cesta-1', 'pb-croissant', 25, 0, 'Prateleira A'),
('inv-pb-rosca-coco', 'comp-cesta-1', 'pb-rosca-coco', 25, 0, 'Prateleira A'),
('inv-bis-trakinas-morango', 'comp-cesta-1', 'bis-trakinas-morango', 25, 0, 'Prateleira A'),
('inv-bis-negresco', 'comp-cesta-1', 'bis-negresco', 25, 0, 'Prateleira A'),
('inv-bis-bono-choc', 'comp-cesta-1', 'bis-bono-choc', 25, 0, 'Prateleira A'),
('inv-bis-passatempo', 'comp-cesta-1', 'bis-passatempo', 25, 0, 'Prateleira A'),
('inv-bis-club-social', 'comp-cesta-1', 'bis-club-social', 25, 0, 'Prateleira A'),
('inv-bis-cream-cracker-adria', 'comp-cesta-1', 'bis-cream-cracker-adria', 25, 0, 'Prateleira A'),
('inv-bis-waffer-bauducco', 'comp-cesta-1', 'bis-waffer-bauducco', 25, 0, 'Prateleira A'),
('inv-fq-queijo-prato-sadia', 'comp-cesta-1', 'fq-queijo-prato-sadia', 25, 0, 'Prateleira A'),
('inv-fq-presunto-seara', 'comp-cesta-1', 'fq-presunto-seara', 25, 0, 'Prateleira A'),
('inv-fq-mussarela-tirolez', 'comp-cesta-1', 'fq-mussarela-tirolez', 25, 0, 'Prateleira A'),
('inv-fq-requeijao-catupiry', 'comp-cesta-1', 'fq-requeijao-catupiry', 25, 0, 'Prateleira A'),
('inv-dg-geleia-queensberry', 'comp-cesta-1', 'dg-geleia-queensberry', 25, 0, 'Prateleira A'),
('inv-dg-nutella-140', 'comp-cesta-1', 'dg-nutella-140', 25, 0, 'Prateleira A'),
('inv-dg-doce-leite-aviacao', 'comp-cesta-1', 'dg-doce-leite-aviacao', 25, 0, 'Prateleira A'),
('inv-dg-mel-karo', 'comp-cesta-1', 'dg-mel-karo', 25, 0, 'Prateleira A'),
('inv-dg-pacoca-yoki', 'comp-cesta-1', 'dg-pacoca-yoki', 25, 0, 'Prateleira A'),
('inv-fr-maca', 'comp-cesta-1', 'fr-maca', 25, 0, 'Prateleira A'),
('inv-fr-banana', 'comp-cesta-1', 'fr-banana', 25, 0, 'Prateleira A'),
('inv-fr-uva-verde', 'comp-cesta-1', 'fr-uva-verde', 25, 0, 'Prateleira A'),
('inv-fr-morango-bandeja', 'comp-cesta-1', 'fr-morango-bandeja', 25, 0, 'Prateleira A'),
('inv-fr-kiwi', 'comp-cesta-1', 'fr-kiwi', 25, 0, 'Prateleira A'),
('inv-mc-cafe-pilao-sache', 'comp-cesta-1', 'mc-cafe-pilao-sache', 25, 0, 'Prateleira A'),
('inv-mc-capuccino-3coracoes', 'comp-cesta-1', 'mc-capuccino-3coracoes', 25, 0, 'Prateleira A'),
('inv-mc-cha-twinings', 'comp-cesta-1', 'mc-cha-twinings', 25, 0, 'Prateleira A'),
('inv-mc-manteiga-aviacao', 'comp-cesta-1', 'mc-manteiga-aviacao', 25, 0, 'Prateleira A'),
('inv-mc-acucar-sache', 'comp-cesta-1', 'mc-acucar-sache', 25, 0, 'Prateleira A'),
('inv-ad-caneca', 'comp-cesta-1', 'ad-caneca', 25, 0, 'Prateleira A'),
('inv-ad-cartao', 'comp-cesta-1', 'ad-cartao', 25, 0, 'Prateleira A'),
('inv-ad-balao', 'comp-cesta-1', 'ad-balao', 25, 0, 'Prateleira A'),
('inv-ad-mini-buque', 'comp-cesta-1', 'ad-mini-buque', 25, 0, 'Prateleira A'),
('inv-ad-espumante', 'comp-cesta-1', 'ad-espumante', 25, 0, 'Prateleira A'),
('inv-ad-vinho-pergola', 'comp-cesta-1', 'ad-vinho-pergola', 25, 0, 'Prateleira A'),
('inv-ad-chocolate-lindt', 'comp-cesta-1', 'ad-chocolate-lindt', 25, 0, 'Prateleira A'),
('inv-ad-taca', 'comp-cesta-1', 'ad-taca', 25, 0, 'Prateleira A')
ON CONFLICT (id) DO UPDATE SET quantity = EXCLUDED.quantity;

-- 8. Lotes com Data de Validade Real
INSERT INTO public.lots (id, company_id, product_id, lot_number, initial_quantity, current_quantity, manufacturing_date, expiration_date, cost_price, status) VALUES
('lot-beb-suco-delvalle-200', 'comp-cesta-1', 'beb-suco-delvalle-200', 'LOT-2026-001', 25, 25, '2026-01-10', '2026-11-05', 2.69, 'active'),
('lot-beb-toddynho-200', 'comp-cesta-1', 'beb-toddynho-200', 'LOT-2026-002', 25, 25, '2026-01-10', '2026-11-20', 1.97, 'active'),
('lot-beb-agua-coco-200', 'comp-cesta-1', 'beb-agua-coco-200', 'LOT-2026-003', 25, 25, '2026-01-10', '2026-12-05', 2.99, 'active'),
('lot-beb-iog-danone-170', 'comp-cesta-1', 'beb-iog-danone-170', 'LOT-2026-004', 25, 25, '2026-01-10', '2026-09-13', 2.27, 'active'),
('lot-beb-ades-500', 'comp-cesta-1', 'beb-ades-500', 'LOT-2026-005', 25, 25, '2026-01-10', '2026-10-21', 3.89, 'active'),
('lot-beb-suco-natone-500', 'comp-cesta-1', 'beb-suco-natone-500', 'LOT-2026-006', 25, 25, '2026-01-10', '2026-09-20', 6.54, 'active'),
('lot-beb-guarana-350', 'comp-cesta-1', 'beb-guarana-350', 'LOT-2026-007', 25, 25, '2026-01-10', '2027-03-05', 2.99, 'active'),
('lot-beb-cha-leao-450', 'comp-cesta-1', 'beb-cha-leao-450', 'LOT-2026-008', 25, 25, '2026-01-10', '2026-12-05', 4.14, 'active'),
('lot-beb-suco-aurora-1l', 'comp-cesta-1', 'beb-suco-aurora-1l', 'LOT-2026-009', 25, 25, '2026-01-10', '2027-01-04', 11.34, 'active'),
('lot-beb-maguary-1l', 'comp-cesta-1', 'beb-maguary-1l', 'LOT-2026-010', 25, 25, '2026-01-10', '2026-12-15', 5.94, 'active'),
('lot-beb-guarana-1l', 'comp-cesta-1', 'beb-guarana-1l', 'LOT-2026-011', 25, 25, '2026-01-10', '2027-03-05', 5.09, 'active'),
('lot-pb-pao-forma-pullman', 'comp-cesta-1', 'pb-pao-forma-pullman', 'LOT-2026-012', 25, 25, '2026-01-10', '2026-09-20', 5.94, 'active'),
('lot-pb-bisnaguinha-wickbold', 'comp-cesta-1', 'pb-bisnaguinha-wickbold', 'LOT-2026-013', 25, 25, '2026-01-10', '2026-09-24', 4.49, 'active'),
('lot-pb-bolo-anamaria', 'comp-cesta-1', 'pb-bolo-anamaria', 'LOT-2026-014', 25, 25, '2026-01-10', '2026-10-06', 2.09, 'active'),
('lot-pb-pao-queijo-fdm', 'comp-cesta-1', 'pb-pao-queijo-fdm', 'LOT-2026-015', 25, 25, '2026-01-10', '2026-12-05', 10.14, 'active'),
('lot-pb-croissant', 'comp-cesta-1', 'pb-croissant', 'LOT-2026-016', 25, 25, '2026-01-10', '2026-09-09', 3.30, 'active'),
('lot-pb-rosca-coco', 'comp-cesta-1', 'pb-rosca-coco', 'LOT-2026-017', 25, 25, '2026-01-10', '2026-09-11', 7.74, 'active'),
('lot-bis-trakinas-morango', 'comp-cesta-1', 'bis-trakinas-morango', 'LOT-2026-018', 25, 25, '2026-01-10', '2027-02-03', 1.91, 'active'),
('lot-bis-negresco', 'comp-cesta-1', 'bis-negresco', 'LOT-2026-019', 25, 25, '2026-01-10', '2027-02-03', 2.09, 'active'),
('lot-bis-bono-choc', 'comp-cesta-1', 'bis-bono-choc', 'LOT-2026-020', 25, 25, '2026-01-10', '2027-02-03', 1.97, 'active'),
('lot-bis-passatempo', 'comp-cesta-1', 'bis-passatempo', 'LOT-2026-021', 25, 25, '2026-01-10', '2027-02-03', 2.03, 'active'),
('lot-bis-club-social', 'comp-cesta-1', 'bis-club-social', 'LOT-2026-022', 25, 25, '2026-01-10', '2026-12-05', 3.29, 'active'),
('lot-bis-cream-cracker-adria', 'comp-cesta-1', 'bis-cream-cracker-adria', 'LOT-2026-023', 25, 25, '2026-01-10', '2027-01-04', 2.57, 'active'),
('lot-bis-waffer-bauducco', 'comp-cesta-1', 'bis-waffer-bauducco', 'LOT-2026-024', 25, 25, '2026-01-10', '2027-02-03', 2.27, 'active'),
('lot-fq-queijo-prato-sadia', 'comp-cesta-1', 'fq-queijo-prato-sadia', 'LOT-2026-025', 25, 25, '2026-01-10', '2026-09-18', 7.74, 'active'),
('lot-fq-presunto-seara', 'comp-cesta-1', 'fq-presunto-seara', 'LOT-2026-026', 25, 25, '2026-01-10', '2026-09-11', 5.94, 'active'),
('lot-fq-mussarela-tirolez', 'comp-cesta-1', 'fq-mussarela-tirolez', 'LOT-2026-027', 25, 25, '2026-01-10', '2026-09-21', 8.10, 'active'),
('lot-fq-requeijao-catupiry', 'comp-cesta-1', 'fq-requeijao-catupiry', 'LOT-2026-028', 25, 25, '2026-01-10', '2026-10-16', 7.14, 'active'),
('lot-dg-geleia-queensberry', 'comp-cesta-1', 'dg-geleia-queensberry', 'LOT-2026-029', 25, 25, '2026-01-10', '2027-07-03', 9.54, 'active'),
('lot-dg-nutella-140', 'comp-cesta-1', 'dg-nutella-140', 'LOT-2026-030', 25, 25, '2026-01-10', '2027-07-03', 8.34, 'active'),
('lot-dg-doce-leite-aviacao', 'comp-cesta-1', 'dg-doce-leite-aviacao', 'LOT-2026-031', 25, 25, '2026-01-10', '2027-07-03', 7.50, 'active'),
('lot-dg-mel-karo', 'comp-cesta-1', 'dg-mel-karo', 'LOT-2026-032', 25, 25, '2026-01-10', '2027-07-03', 8.94, 'active'),
('lot-dg-pacoca-yoki', 'comp-cesta-1', 'dg-pacoca-yoki', 'LOT-2026-033', 25, 25, '2026-01-10', '2027-07-03', 0.77, 'active'),
('lot-fr-maca', 'comp-cesta-1', 'fr-maca', 'LOT-2026-034', 25, 25, '2026-01-10', '2026-09-18', 1.19, 'active'),
('lot-fr-banana', 'comp-cesta-1', 'fr-banana', 'LOT-2026-035', 25, 25, '2026-01-10', '2026-09-18', 0.77, 'active'),
('lot-fr-uva-verde', 'comp-cesta-1', 'fr-uva-verde', 'LOT-2026-036', 25, 25, '2026-01-10', '2026-09-18', 4.14, 'active'),
('lot-fr-morango-bandeja', 'comp-cesta-1', 'fr-morango-bandeja', 'LOT-2026-037', 25, 25, '2026-01-10', '2026-09-18', 5.94, 'active'),
('lot-fr-kiwi', 'comp-cesta-1', 'fr-kiwi', 'LOT-2026-038', 25, 25, '2026-01-10', '2026-09-18', 1.49, 'active'),
('lot-mc-cafe-pilao-sache', 'comp-cesta-1', 'mc-cafe-pilao-sache', 'LOT-2026-039', 25, 25, '2026-01-10', '2026-11-05', 0.89, 'active'),
('lot-mc-capuccino-3coracoes', 'comp-cesta-1', 'mc-capuccino-3coracoes', 'LOT-2026-040', 25, 25, '2026-01-10', '2026-11-05', 1.49, 'active'),
('lot-mc-cha-twinings', 'comp-cesta-1', 'mc-cha-twinings', 'LOT-2026-041', 25, 25, '2026-01-10', '2026-11-05', 7.14, 'active'),
('lot-mc-manteiga-aviacao', 'comp-cesta-1', 'mc-manteiga-aviacao', 'LOT-2026-042', 25, 25, '2026-01-10', '2026-11-05', 8.34, 'active'),
('lot-mc-acucar-sache', 'comp-cesta-1', 'mc-acucar-sache', 'LOT-2026-043', 25, 25, '2026-01-10', '2026-11-05', 2.34, 'active'),
('lot-ad-caneca', 'comp-cesta-1', 'ad-caneca', 'LOT-2026-044', 25, 25, '2026-01-10', '2026-11-05', 14.94, 'active'),
('lot-ad-cartao', 'comp-cesta-1', 'ad-cartao', 'LOT-2026-045', 25, 25, '2026-01-10', '2026-11-05', 3.00, 'active'),
('lot-ad-balao', 'comp-cesta-1', 'ad-balao', 'LOT-2026-046', 25, 25, '2026-01-10', '2026-11-05', 8.94, 'active'),
('lot-ad-mini-buque', 'comp-cesta-1', 'ad-mini-buque', 'LOT-2026-047', 25, 25, '2026-01-10', '2026-11-05', 17.94, 'active'),
('lot-ad-espumante', 'comp-cesta-1', 'ad-espumante', 'LOT-2026-048', 25, 25, '2026-01-10', '2026-11-05', 13.74, 'active'),
('lot-ad-vinho-pergola', 'comp-cesta-1', 'ad-vinho-pergola', 'LOT-2026-049', 25, 25, '2026-01-10', '2026-11-05', 17.94, 'active'),
('lot-ad-chocolate-lindt', 'comp-cesta-1', 'ad-chocolate-lindt', 'LOT-2026-050', 25, 25, '2026-01-10', '2026-11-05', 20.94, 'active'),
('lot-ad-taca', 'comp-cesta-1', 'ad-taca', 'LOT-2026-051', 25, 25, '2026-01-10', '2026-11-05', 11.94, 'active')
ON CONFLICT (id) DO UPDATE SET expiration_date = EXCLUDED.expiration_date;
